#:schema node_modules/wrangler/config-schema.json
name = "sh0rt-kr-email-worker"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VARIABLE = "production_value"

# Bind an Analytics Engine dataset. Use Analytics Engine to write analytics within your Pages Function.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#analytics-engine-datasets
# [[analytics_engine_datasets]]
# binding = "MY_DATASET"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
# [[queues.producers]]
# binding = "EMAIL_QUEUE"
# queue = "sh0rt-kr-email-worker"

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues

[[r2_buckets]]
binding = "R2"
bucket_name = "sh0rt-kr-email"

[[d1_databases]]
binding = "DB"
database_name = "sh0rt-kr-email"
database_id = "bc4ea5b5-6434-4fae-bf01-5c201ee60dc1"


[[queues.consumers]]
queue = "sh0rt-kr-email-worker"

